

runtime: go116
env: standard


instance_class: F1
handlers:
  - url: .*
    secure: always
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
service_account: dwio-hack-nyu-2022@appspot.gserviceaccount.com

app_engine_apis: true
