
runtime: go115
env: standard
instance_class: F1
handlers:
  - url: .*
    secure: always
    script: auto
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
service_account: dwio-hack-nyu-2022@appspot.gserviceaccount.com
